import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import '@/app/api/api.js'
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OTL - PUP LQC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <Script src="api.js" strategy="lazyOnload"></Script>
      </body>
    </html>
  );
}
